/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-13 at 01:54:58 UTC 
 * Modify at your own risk.
 */

package com.masdar.entities.socialideauserendpoint;

/**
 * Service definition for Socialideauserendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link SocialideauserendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Socialideauserendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the socialideauserendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://masdarengine.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "socialideauserendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Socialideauserendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Socialideauserendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getSocialIdeaUser".
   *
   * This request holds the parameters needed by the the socialideauserendpoint server.  After setting
   * any optional parameters, call the {@link GetSocialIdeaUser#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetSocialIdeaUser getSocialIdeaUser(java.lang.Long id) throws java.io.IOException {
    GetSocialIdeaUser result = new GetSocialIdeaUser(id);
    initialize(result);
    return result;
  }

  public class GetSocialIdeaUser extends SocialideauserendpointRequest<com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser> {

    private static final String REST_PATH = "socialideauser/{id}";

    /**
     * Create a request for the method "getSocialIdeaUser".
     *
     * This request holds the parameters needed by the the socialideauserendpoint server.  After
     * setting any optional parameters, call the {@link GetSocialIdeaUser#execute()} method to invoke
     * the remote operation. <p> {@link GetSocialIdeaUser#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetSocialIdeaUser(java.lang.Long id) {
      super(Socialideauserendpoint.this, "GET", REST_PATH, null, com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetSocialIdeaUser setAlt(java.lang.String alt) {
      return (GetSocialIdeaUser) super.setAlt(alt);
    }

    @Override
    public GetSocialIdeaUser setFields(java.lang.String fields) {
      return (GetSocialIdeaUser) super.setFields(fields);
    }

    @Override
    public GetSocialIdeaUser setKey(java.lang.String key) {
      return (GetSocialIdeaUser) super.setKey(key);
    }

    @Override
    public GetSocialIdeaUser setOauthToken(java.lang.String oauthToken) {
      return (GetSocialIdeaUser) super.setOauthToken(oauthToken);
    }

    @Override
    public GetSocialIdeaUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetSocialIdeaUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetSocialIdeaUser setQuotaUser(java.lang.String quotaUser) {
      return (GetSocialIdeaUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetSocialIdeaUser setUserIp(java.lang.String userIp) {
      return (GetSocialIdeaUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetSocialIdeaUser setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetSocialIdeaUser set(String parameterName, Object value) {
      return (GetSocialIdeaUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getUserRole".
   *
   * This request holds the parameters needed by the the socialideauserendpoint server.  After setting
   * any optional parameters, call the {@link GetUserRole#execute()} method to invoke the remote
   * operation.
   *
   * @param ideaId
   * @param userId
   * @return the request
   */
  public GetUserRole getUserRole(java.lang.Long ideaId, java.lang.Long userId) throws java.io.IOException {
    GetUserRole result = new GetUserRole(ideaId, userId);
    initialize(result);
    return result;
  }

  public class GetUserRole extends SocialideauserendpointRequest<com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser> {

    private static final String REST_PATH = "socialideauser/{ideaId}/{userId}";

    /**
     * Create a request for the method "getUserRole".
     *
     * This request holds the parameters needed by the the socialideauserendpoint server.  After
     * setting any optional parameters, call the {@link GetUserRole#execute()} method to invoke the
     * remote operation. <p> {@link
     * GetUserRole#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param ideaId
     * @param userId
     * @since 1.13
     */
    protected GetUserRole(java.lang.Long ideaId, java.lang.Long userId) {
      super(Socialideauserendpoint.this, "GET", REST_PATH, null, com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser.class);
      this.ideaId = com.google.api.client.util.Preconditions.checkNotNull(ideaId, "Required parameter ideaId must be specified.");
      this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetUserRole setAlt(java.lang.String alt) {
      return (GetUserRole) super.setAlt(alt);
    }

    @Override
    public GetUserRole setFields(java.lang.String fields) {
      return (GetUserRole) super.setFields(fields);
    }

    @Override
    public GetUserRole setKey(java.lang.String key) {
      return (GetUserRole) super.setKey(key);
    }

    @Override
    public GetUserRole setOauthToken(java.lang.String oauthToken) {
      return (GetUserRole) super.setOauthToken(oauthToken);
    }

    @Override
    public GetUserRole setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetUserRole) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetUserRole setQuotaUser(java.lang.String quotaUser) {
      return (GetUserRole) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetUserRole setUserIp(java.lang.String userIp) {
      return (GetUserRole) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long ideaId;

    /**

     */
    public java.lang.Long getIdeaId() {
      return ideaId;
    }

    public GetUserRole setIdeaId(java.lang.Long ideaId) {
      this.ideaId = ideaId;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long userId;

    /**

     */
    public java.lang.Long getUserId() {
      return userId;
    }

    public GetUserRole setUserId(java.lang.Long userId) {
      this.userId = userId;
      return this;
    }

    @Override
    public GetUserRole set(String parameterName, Object value) {
      return (GetUserRole) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertSocialIdeaUser".
   *
   * This request holds the parameters needed by the the socialideauserendpoint server.  After setting
   * any optional parameters, call the {@link InsertSocialIdeaUser#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser}
   * @return the request
   */
  public InsertSocialIdeaUser insertSocialIdeaUser(com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser content) throws java.io.IOException {
    InsertSocialIdeaUser result = new InsertSocialIdeaUser(content);
    initialize(result);
    return result;
  }

  public class InsertSocialIdeaUser extends SocialideauserendpointRequest<com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser> {

    private static final String REST_PATH = "socialideauser";

    /**
     * Create a request for the method "insertSocialIdeaUser".
     *
     * This request holds the parameters needed by the the socialideauserendpoint server.  After
     * setting any optional parameters, call the {@link InsertSocialIdeaUser#execute()} method to
     * invoke the remote operation. <p> {@link InsertSocialIdeaUser#initialize(com.google.api.client.g
     * oogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser}
     * @since 1.13
     */
    protected InsertSocialIdeaUser(com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser content) {
      super(Socialideauserendpoint.this, "POST", REST_PATH, content, com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser.class);
    }

    @Override
    public InsertSocialIdeaUser setAlt(java.lang.String alt) {
      return (InsertSocialIdeaUser) super.setAlt(alt);
    }

    @Override
    public InsertSocialIdeaUser setFields(java.lang.String fields) {
      return (InsertSocialIdeaUser) super.setFields(fields);
    }

    @Override
    public InsertSocialIdeaUser setKey(java.lang.String key) {
      return (InsertSocialIdeaUser) super.setKey(key);
    }

    @Override
    public InsertSocialIdeaUser setOauthToken(java.lang.String oauthToken) {
      return (InsertSocialIdeaUser) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertSocialIdeaUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertSocialIdeaUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertSocialIdeaUser setQuotaUser(java.lang.String quotaUser) {
      return (InsertSocialIdeaUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertSocialIdeaUser setUserIp(java.lang.String userIp) {
      return (InsertSocialIdeaUser) super.setUserIp(userIp);
    }

    @Override
    public InsertSocialIdeaUser set(String parameterName, Object value) {
      return (InsertSocialIdeaUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listSocialIdeaUser".
   *
   * This request holds the parameters needed by the the socialideauserendpoint server.  After setting
   * any optional parameters, call the {@link ListSocialIdeaUser#execute()} method to invoke the
   * remote operation.
   *
   * @return the request
   */
  public ListSocialIdeaUser listSocialIdeaUser() throws java.io.IOException {
    ListSocialIdeaUser result = new ListSocialIdeaUser();
    initialize(result);
    return result;
  }

  public class ListSocialIdeaUser extends SocialideauserendpointRequest<com.masdar.entities.socialideauserendpoint.model.CollectionResponseSocialIdeaUser> {

    private static final String REST_PATH = "socialideauser";

    /**
     * Create a request for the method "listSocialIdeaUser".
     *
     * This request holds the parameters needed by the the socialideauserendpoint server.  After
     * setting any optional parameters, call the {@link ListSocialIdeaUser#execute()} method to invoke
     * the remote operation. <p> {@link ListSocialIdeaUser#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListSocialIdeaUser() {
      super(Socialideauserendpoint.this, "GET", REST_PATH, null, com.masdar.entities.socialideauserendpoint.model.CollectionResponseSocialIdeaUser.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListSocialIdeaUser setAlt(java.lang.String alt) {
      return (ListSocialIdeaUser) super.setAlt(alt);
    }

    @Override
    public ListSocialIdeaUser setFields(java.lang.String fields) {
      return (ListSocialIdeaUser) super.setFields(fields);
    }

    @Override
    public ListSocialIdeaUser setKey(java.lang.String key) {
      return (ListSocialIdeaUser) super.setKey(key);
    }

    @Override
    public ListSocialIdeaUser setOauthToken(java.lang.String oauthToken) {
      return (ListSocialIdeaUser) super.setOauthToken(oauthToken);
    }

    @Override
    public ListSocialIdeaUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListSocialIdeaUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListSocialIdeaUser setQuotaUser(java.lang.String quotaUser) {
      return (ListSocialIdeaUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListSocialIdeaUser setUserIp(java.lang.String userIp) {
      return (ListSocialIdeaUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListSocialIdeaUser setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListSocialIdeaUser setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListSocialIdeaUser set(String parameterName, Object value) {
      return (ListSocialIdeaUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeSocialIdeaUser".
   *
   * This request holds the parameters needed by the the socialideauserendpoint server.  After setting
   * any optional parameters, call the {@link RemoveSocialIdeaUser#execute()} method to invoke the
   * remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveSocialIdeaUser removeSocialIdeaUser(java.lang.Long id) throws java.io.IOException {
    RemoveSocialIdeaUser result = new RemoveSocialIdeaUser(id);
    initialize(result);
    return result;
  }

  public class RemoveSocialIdeaUser extends SocialideauserendpointRequest<Void> {

    private static final String REST_PATH = "socialideauser/{id}";

    /**
     * Create a request for the method "removeSocialIdeaUser".
     *
     * This request holds the parameters needed by the the socialideauserendpoint server.  After
     * setting any optional parameters, call the {@link RemoveSocialIdeaUser#execute()} method to
     * invoke the remote operation. <p> {@link RemoveSocialIdeaUser#initialize(com.google.api.client.g
     * oogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveSocialIdeaUser(java.lang.Long id) {
      super(Socialideauserendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveSocialIdeaUser setAlt(java.lang.String alt) {
      return (RemoveSocialIdeaUser) super.setAlt(alt);
    }

    @Override
    public RemoveSocialIdeaUser setFields(java.lang.String fields) {
      return (RemoveSocialIdeaUser) super.setFields(fields);
    }

    @Override
    public RemoveSocialIdeaUser setKey(java.lang.String key) {
      return (RemoveSocialIdeaUser) super.setKey(key);
    }

    @Override
    public RemoveSocialIdeaUser setOauthToken(java.lang.String oauthToken) {
      return (RemoveSocialIdeaUser) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveSocialIdeaUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveSocialIdeaUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveSocialIdeaUser setQuotaUser(java.lang.String quotaUser) {
      return (RemoveSocialIdeaUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveSocialIdeaUser setUserIp(java.lang.String userIp) {
      return (RemoveSocialIdeaUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveSocialIdeaUser setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveSocialIdeaUser set(String parameterName, Object value) {
      return (RemoveSocialIdeaUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateSocialIdeaUser".
   *
   * This request holds the parameters needed by the the socialideauserendpoint server.  After setting
   * any optional parameters, call the {@link UpdateSocialIdeaUser#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser}
   * @return the request
   */
  public UpdateSocialIdeaUser updateSocialIdeaUser(com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser content) throws java.io.IOException {
    UpdateSocialIdeaUser result = new UpdateSocialIdeaUser(content);
    initialize(result);
    return result;
  }

  public class UpdateSocialIdeaUser extends SocialideauserendpointRequest<com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser> {

    private static final String REST_PATH = "socialideauser";

    /**
     * Create a request for the method "updateSocialIdeaUser".
     *
     * This request holds the parameters needed by the the socialideauserendpoint server.  After
     * setting any optional parameters, call the {@link UpdateSocialIdeaUser#execute()} method to
     * invoke the remote operation. <p> {@link UpdateSocialIdeaUser#initialize(com.google.api.client.g
     * oogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser}
     * @since 1.13
     */
    protected UpdateSocialIdeaUser(com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser content) {
      super(Socialideauserendpoint.this, "PUT", REST_PATH, content, com.masdar.entities.socialideauserendpoint.model.SocialIdeaUser.class);
    }

    @Override
    public UpdateSocialIdeaUser setAlt(java.lang.String alt) {
      return (UpdateSocialIdeaUser) super.setAlt(alt);
    }

    @Override
    public UpdateSocialIdeaUser setFields(java.lang.String fields) {
      return (UpdateSocialIdeaUser) super.setFields(fields);
    }

    @Override
    public UpdateSocialIdeaUser setKey(java.lang.String key) {
      return (UpdateSocialIdeaUser) super.setKey(key);
    }

    @Override
    public UpdateSocialIdeaUser setOauthToken(java.lang.String oauthToken) {
      return (UpdateSocialIdeaUser) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateSocialIdeaUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateSocialIdeaUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateSocialIdeaUser setQuotaUser(java.lang.String quotaUser) {
      return (UpdateSocialIdeaUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateSocialIdeaUser setUserIp(java.lang.String userIp) {
      return (UpdateSocialIdeaUser) super.setUserIp(userIp);
    }

    @Override
    public UpdateSocialIdeaUser set(String parameterName, Object value) {
      return (UpdateSocialIdeaUser) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Socialideauserendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Socialideauserendpoint}. */
    @Override
    public Socialideauserendpoint build() {
      return new Socialideauserendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link SocialideauserendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setSocialideauserendpointRequestInitializer(
        SocialideauserendpointRequestInitializer socialideauserendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(socialideauserendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
