{
	"installed":
	{
		"auth_uri":"https://accounts.google.com/o/oauth2/auth",
		"token_uri":"https://accounts.google.com/o/oauth2/token",
		"client_email":"",
		"redirect_uris":["urn:ietf:wg:oauth:2.0:oob","oob"],
		"client_x509_cert_url":"",
		"client_id":"966286397243-o2e69qfgqc5pb59pdvvk0v68l6ah9kba.apps.googleusercontent.com",
		"auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs"
	}
}
