/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-13 at 01:54:58 UTC 
 * Modify at your own risk.
 */

package com.masdar.entities.socialideauserendpoint.model;

/**
 * Model definition for SocialIdeaUser.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the socialideauserendpoint. For a detailed explanation
 * see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SocialIdeaUser extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("idea_id") @com.google.api.client.json.JsonString
  private java.lang.Long ideaId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer isLocked;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("role_id")
  private java.lang.Integer roleId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("social_idea_user_id") @com.google.api.client.json.JsonString
  private java.lang.Long socialIdeaUserId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("user_id") @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdeaId() {
    return ideaId;
  }

  /**
   * @param ideaId ideaId or {@code null} for none
   */
  public SocialIdeaUser setIdeaId(java.lang.Long ideaId) {
    this.ideaId = ideaId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIsLocked() {
    return isLocked;
  }

  /**
   * @param isLocked isLocked or {@code null} for none
   */
  public SocialIdeaUser setIsLocked(java.lang.Integer isLocked) {
    this.isLocked = isLocked;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getRoleId() {
    return roleId;
  }

  /**
   * @param roleId roleId or {@code null} for none
   */
  public SocialIdeaUser setRoleId(java.lang.Integer roleId) {
    this.roleId = roleId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getSocialIdeaUserId() {
    return socialIdeaUserId;
  }

  /**
   * @param socialIdeaUserId socialIdeaUserId or {@code null} for none
   */
  public SocialIdeaUser setSocialIdeaUserId(java.lang.Long socialIdeaUserId) {
    this.socialIdeaUserId = socialIdeaUserId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public SocialIdeaUser setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public SocialIdeaUser set(String fieldName, Object value) {
    return (SocialIdeaUser) super.set(fieldName, value);
  }

  @Override
  public SocialIdeaUser clone() {
    return (SocialIdeaUser) super.clone();
  }

}
