/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-13 at 01:53:09 UTC 
 * Modify at your own risk.
 */

package com.masdar.entities.userendpoint.model;

/**
 * Model definition for User.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the userendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class User extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("device_id")
  private java.lang.String deviceId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("fb_id") @com.google.api.client.json.JsonString
  private java.lang.Long fbId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("gplus_id") @com.google.api.client.json.JsonString
  private java.lang.Long gplusId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("join_date")
  private java.lang.String joinDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("mob_no")
  private java.lang.String mobNo;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("profile_pic")
  private java.lang.String profilePic;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("user_id") @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("user_name")
  private java.lang.String userName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeviceId() {
    return deviceId;
  }

  /**
   * @param deviceId deviceId or {@code null} for none
   */
  public User setDeviceId(java.lang.String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public User setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getFbId() {
    return fbId;
  }

  /**
   * @param fbId fbId or {@code null} for none
   */
  public User setFbId(java.lang.Long fbId) {
    this.fbId = fbId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getGplusId() {
    return gplusId;
  }

  /**
   * @param gplusId gplusId or {@code null} for none
   */
  public User setGplusId(java.lang.Long gplusId) {
    this.gplusId = gplusId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getJoinDate() {
    return joinDate;
  }

  /**
   * @param joinDate joinDate or {@code null} for none
   */
  public User setJoinDate(java.lang.String joinDate) {
    this.joinDate = joinDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMobNo() {
    return mobNo;
  }

  /**
   * @param mobNo mobNo or {@code null} for none
   */
  public User setMobNo(java.lang.String mobNo) {
    this.mobNo = mobNo;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProfilePic() {
    return profilePic;
  }

  /**
   * @param profilePic profilePic or {@code null} for none
   */
  public User setProfilePic(java.lang.String profilePic) {
    this.profilePic = profilePic;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public User setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserName() {
    return userName;
  }

  /**
   * @param userName userName or {@code null} for none
   */
  public User setUserName(java.lang.String userName) {
    this.userName = userName;
    return this;
  }

  @Override
  public User set(String fieldName, Object value) {
    return (User) super.set(fieldName, value);
  }

  @Override
  public User clone() {
    return (User) super.clone();
  }

}
