/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-13 at 01:53:40 UTC 
 * Modify at your own risk.
 */

package com.masdar.entities.testentityendpoint;

/**
 * Service definition for Testentityendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link TestentityendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Testentityendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the testentityendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://masdarengine.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "testentityendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Testentityendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Testentityendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getTestEntity".
   *
   * This request holds the parameters needed by the the testentityendpoint server.  After setting any
   * optional parameters, call the {@link GetTestEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetTestEntity getTestEntity(java.lang.Long id) throws java.io.IOException {
    GetTestEntity result = new GetTestEntity(id);
    initialize(result);
    return result;
  }

  public class GetTestEntity extends TestentityendpointRequest<com.masdar.entities.testentityendpoint.model.TestEntity> {

    private static final String REST_PATH = "testentity/{id}";

    /**
     * Create a request for the method "getTestEntity".
     *
     * This request holds the parameters needed by the the testentityendpoint server.  After setting
     * any optional parameters, call the {@link GetTestEntity#execute()} method to invoke the remote
     * operation. <p> {@link GetTestEntity#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetTestEntity(java.lang.Long id) {
      super(Testentityendpoint.this, "GET", REST_PATH, null, com.masdar.entities.testentityendpoint.model.TestEntity.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetTestEntity setAlt(java.lang.String alt) {
      return (GetTestEntity) super.setAlt(alt);
    }

    @Override
    public GetTestEntity setFields(java.lang.String fields) {
      return (GetTestEntity) super.setFields(fields);
    }

    @Override
    public GetTestEntity setKey(java.lang.String key) {
      return (GetTestEntity) super.setKey(key);
    }

    @Override
    public GetTestEntity setOauthToken(java.lang.String oauthToken) {
      return (GetTestEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public GetTestEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetTestEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetTestEntity setQuotaUser(java.lang.String quotaUser) {
      return (GetTestEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetTestEntity setUserIp(java.lang.String userIp) {
      return (GetTestEntity) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetTestEntity setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetTestEntity set(String parameterName, Object value) {
      return (GetTestEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertTestEntity".
   *
   * This request holds the parameters needed by the the testentityendpoint server.  After setting any
   * optional parameters, call the {@link InsertTestEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.masdar.entities.testentityendpoint.model.TestEntity}
   * @return the request
   */
  public InsertTestEntity insertTestEntity(com.masdar.entities.testentityendpoint.model.TestEntity content) throws java.io.IOException {
    InsertTestEntity result = new InsertTestEntity(content);
    initialize(result);
    return result;
  }

  public class InsertTestEntity extends TestentityendpointRequest<com.masdar.entities.testentityendpoint.model.TestEntity> {

    private static final String REST_PATH = "testentity";

    /**
     * Create a request for the method "insertTestEntity".
     *
     * This request holds the parameters needed by the the testentityendpoint server.  After setting
     * any optional parameters, call the {@link InsertTestEntity#execute()} method to invoke the
     * remote operation. <p> {@link InsertTestEntity#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.masdar.entities.testentityendpoint.model.TestEntity}
     * @since 1.13
     */
    protected InsertTestEntity(com.masdar.entities.testentityendpoint.model.TestEntity content) {
      super(Testentityendpoint.this, "POST", REST_PATH, content, com.masdar.entities.testentityendpoint.model.TestEntity.class);
    }

    @Override
    public InsertTestEntity setAlt(java.lang.String alt) {
      return (InsertTestEntity) super.setAlt(alt);
    }

    @Override
    public InsertTestEntity setFields(java.lang.String fields) {
      return (InsertTestEntity) super.setFields(fields);
    }

    @Override
    public InsertTestEntity setKey(java.lang.String key) {
      return (InsertTestEntity) super.setKey(key);
    }

    @Override
    public InsertTestEntity setOauthToken(java.lang.String oauthToken) {
      return (InsertTestEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertTestEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertTestEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertTestEntity setQuotaUser(java.lang.String quotaUser) {
      return (InsertTestEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertTestEntity setUserIp(java.lang.String userIp) {
      return (InsertTestEntity) super.setUserIp(userIp);
    }

    @Override
    public InsertTestEntity set(String parameterName, Object value) {
      return (InsertTestEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listTestEntity".
   *
   * This request holds the parameters needed by the the testentityendpoint server.  After setting any
   * optional parameters, call the {@link ListTestEntity#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListTestEntity listTestEntity() throws java.io.IOException {
    ListTestEntity result = new ListTestEntity();
    initialize(result);
    return result;
  }

  public class ListTestEntity extends TestentityendpointRequest<com.masdar.entities.testentityendpoint.model.CollectionResponseTestEntity> {

    private static final String REST_PATH = "testentity";

    /**
     * Create a request for the method "listTestEntity".
     *
     * This request holds the parameters needed by the the testentityendpoint server.  After setting
     * any optional parameters, call the {@link ListTestEntity#execute()} method to invoke the remote
     * operation. <p> {@link ListTestEntity#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListTestEntity() {
      super(Testentityendpoint.this, "GET", REST_PATH, null, com.masdar.entities.testentityendpoint.model.CollectionResponseTestEntity.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListTestEntity setAlt(java.lang.String alt) {
      return (ListTestEntity) super.setAlt(alt);
    }

    @Override
    public ListTestEntity setFields(java.lang.String fields) {
      return (ListTestEntity) super.setFields(fields);
    }

    @Override
    public ListTestEntity setKey(java.lang.String key) {
      return (ListTestEntity) super.setKey(key);
    }

    @Override
    public ListTestEntity setOauthToken(java.lang.String oauthToken) {
      return (ListTestEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public ListTestEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListTestEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListTestEntity setQuotaUser(java.lang.String quotaUser) {
      return (ListTestEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListTestEntity setUserIp(java.lang.String userIp) {
      return (ListTestEntity) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListTestEntity setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListTestEntity setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListTestEntity set(String parameterName, Object value) {
      return (ListTestEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeTestEntity".
   *
   * This request holds the parameters needed by the the testentityendpoint server.  After setting any
   * optional parameters, call the {@link RemoveTestEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveTestEntity removeTestEntity(java.lang.Long id) throws java.io.IOException {
    RemoveTestEntity result = new RemoveTestEntity(id);
    initialize(result);
    return result;
  }

  public class RemoveTestEntity extends TestentityendpointRequest<Void> {

    private static final String REST_PATH = "testentity/{id}";

    /**
     * Create a request for the method "removeTestEntity".
     *
     * This request holds the parameters needed by the the testentityendpoint server.  After setting
     * any optional parameters, call the {@link RemoveTestEntity#execute()} method to invoke the
     * remote operation. <p> {@link RemoveTestEntity#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveTestEntity(java.lang.Long id) {
      super(Testentityendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveTestEntity setAlt(java.lang.String alt) {
      return (RemoveTestEntity) super.setAlt(alt);
    }

    @Override
    public RemoveTestEntity setFields(java.lang.String fields) {
      return (RemoveTestEntity) super.setFields(fields);
    }

    @Override
    public RemoveTestEntity setKey(java.lang.String key) {
      return (RemoveTestEntity) super.setKey(key);
    }

    @Override
    public RemoveTestEntity setOauthToken(java.lang.String oauthToken) {
      return (RemoveTestEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveTestEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveTestEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveTestEntity setQuotaUser(java.lang.String quotaUser) {
      return (RemoveTestEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveTestEntity setUserIp(java.lang.String userIp) {
      return (RemoveTestEntity) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveTestEntity setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveTestEntity set(String parameterName, Object value) {
      return (RemoveTestEntity) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateTestEntity".
   *
   * This request holds the parameters needed by the the testentityendpoint server.  After setting any
   * optional parameters, call the {@link UpdateTestEntity#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.masdar.entities.testentityendpoint.model.TestEntity}
   * @return the request
   */
  public UpdateTestEntity updateTestEntity(com.masdar.entities.testentityendpoint.model.TestEntity content) throws java.io.IOException {
    UpdateTestEntity result = new UpdateTestEntity(content);
    initialize(result);
    return result;
  }

  public class UpdateTestEntity extends TestentityendpointRequest<com.masdar.entities.testentityendpoint.model.TestEntity> {

    private static final String REST_PATH = "testentity";

    /**
     * Create a request for the method "updateTestEntity".
     *
     * This request holds the parameters needed by the the testentityendpoint server.  After setting
     * any optional parameters, call the {@link UpdateTestEntity#execute()} method to invoke the
     * remote operation. <p> {@link UpdateTestEntity#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.masdar.entities.testentityendpoint.model.TestEntity}
     * @since 1.13
     */
    protected UpdateTestEntity(com.masdar.entities.testentityendpoint.model.TestEntity content) {
      super(Testentityendpoint.this, "PUT", REST_PATH, content, com.masdar.entities.testentityendpoint.model.TestEntity.class);
    }

    @Override
    public UpdateTestEntity setAlt(java.lang.String alt) {
      return (UpdateTestEntity) super.setAlt(alt);
    }

    @Override
    public UpdateTestEntity setFields(java.lang.String fields) {
      return (UpdateTestEntity) super.setFields(fields);
    }

    @Override
    public UpdateTestEntity setKey(java.lang.String key) {
      return (UpdateTestEntity) super.setKey(key);
    }

    @Override
    public UpdateTestEntity setOauthToken(java.lang.String oauthToken) {
      return (UpdateTestEntity) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateTestEntity setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateTestEntity) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateTestEntity setQuotaUser(java.lang.String quotaUser) {
      return (UpdateTestEntity) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateTestEntity setUserIp(java.lang.String userIp) {
      return (UpdateTestEntity) super.setUserIp(userIp);
    }

    @Override
    public UpdateTestEntity set(String parameterName, Object value) {
      return (UpdateTestEntity) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Testentityendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Testentityendpoint}. */
    @Override
    public Testentityendpoint build() {
      return new Testentityendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link TestentityendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setTestentityendpointRequestInitializer(
        TestentityendpointRequestInitializer testentityendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(testentityendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
