/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-13 at 01:56:22 UTC 
 * Modify at your own risk.
 */

package com.masdar.entities.votinguserendpoint.model;

/**
 * Model definition for VotingUser.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the votinguserendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class VotingUser extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("vote_id") @com.google.api.client.json.JsonString
  private java.lang.Long voteId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("vote_idea_id") @com.google.api.client.json.JsonString
  private java.lang.Long voteIdeaId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("vote_type")
  private java.lang.Integer voteType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("vote_user_id") @com.google.api.client.json.JsonString
  private java.lang.Long voteUserId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getVoteId() {
    return voteId;
  }

  /**
   * @param voteId voteId or {@code null} for none
   */
  public VotingUser setVoteId(java.lang.Long voteId) {
    this.voteId = voteId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getVoteIdeaId() {
    return voteIdeaId;
  }

  /**
   * @param voteIdeaId voteIdeaId or {@code null} for none
   */
  public VotingUser setVoteIdeaId(java.lang.Long voteIdeaId) {
    this.voteIdeaId = voteIdeaId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getVoteType() {
    return voteType;
  }

  /**
   * @param voteType voteType or {@code null} for none
   */
  public VotingUser setVoteType(java.lang.Integer voteType) {
    this.voteType = voteType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getVoteUserId() {
    return voteUserId;
  }

  /**
   * @param voteUserId voteUserId or {@code null} for none
   */
  public VotingUser setVoteUserId(java.lang.Long voteUserId) {
    this.voteUserId = voteUserId;
    return this;
  }

  @Override
  public VotingUser set(String fieldName, Object value) {
    return (VotingUser) super.set(fieldName, value);
  }

  @Override
  public VotingUser clone() {
    return (VotingUser) super.clone();
  }

}
