/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-13 at 01:55:38 UTC 
 * Modify at your own risk.
 */

package com.masdar.entities.ideaendpoint.model;

/**
 * Model definition for Idea.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the ideaendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Idea extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("idea_blob_key")
  private java.lang.String ideaBlobKey;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("idea_header")
  private java.lang.String ideaHeader;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("idea_id") @com.google.api.client.json.JsonString
  private java.lang.Long ideaId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("idea_type")
  private java.lang.Integer ideaType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("user_id") @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("voting_number") @com.google.api.client.json.JsonString
  private java.lang.Long votingNumber;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdeaBlobKey() {
    return ideaBlobKey;
  }

  /**
   * @param ideaBlobKey ideaBlobKey or {@code null} for none
   */
  public Idea setIdeaBlobKey(java.lang.String ideaBlobKey) {
    this.ideaBlobKey = ideaBlobKey;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIdeaHeader() {
    return ideaHeader;
  }

  /**
   * @param ideaHeader ideaHeader or {@code null} for none
   */
  public Idea setIdeaHeader(java.lang.String ideaHeader) {
    this.ideaHeader = ideaHeader;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdeaId() {
    return ideaId;
  }

  /**
   * @param ideaId ideaId or {@code null} for none
   */
  public Idea setIdeaId(java.lang.Long ideaId) {
    this.ideaId = ideaId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIdeaType() {
    return ideaType;
  }

  /**
   * @param ideaType ideaType or {@code null} for none
   */
  public Idea setIdeaType(java.lang.Integer ideaType) {
    this.ideaType = ideaType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public Idea setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getVotingNumber() {
    return votingNumber;
  }

  /**
   * @param votingNumber votingNumber or {@code null} for none
   */
  public Idea setVotingNumber(java.lang.Long votingNumber) {
    this.votingNumber = votingNumber;
    return this;
  }

  @Override
  public Idea set(String fieldName, Object value) {
    return (Idea) super.set(fieldName, value);
  }

  @Override
  public Idea clone() {
    return (Idea) super.clone();
  }

}
