/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-13 at 01:55:38 UTC 
 * Modify at your own risk.
 */

package com.masdar.entities.ideaendpoint.model;

/**
 * Model definition for TransactionResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the ideaendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class TransactionResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String errMessage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean valid;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getErrMessage() {
    return errMessage;
  }

  /**
   * @param errMessage errMessage or {@code null} for none
   */
  public TransactionResponse setErrMessage(java.lang.String errMessage) {
    this.errMessage = errMessage;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getValid() {
    return valid;
  }

  /**
   * @param valid valid or {@code null} for none
   */
  public TransactionResponse setValid(java.lang.Boolean valid) {
    this.valid = valid;
    return this;
  }

  @Override
  public TransactionResponse set(String fieldName, Object value) {
    return (TransactionResponse) super.set(fieldName, value);
  }

  @Override
  public TransactionResponse clone() {
    return (TransactionResponse) super.clone();
  }

}
